# Site settings
title: Joe Ridgway
email: joe.e.ridgway@gmail.com
description: "Joe Ridgway's official spot online."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 54C2FF #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jeridgway
  - title: facebook
    url: https://www.facebook.com/joseph.ridgway
  - title: stack-overflow
    url: http://stackoverflow.com/users/524458/joseph-ridgway
  - title: github
    url: http://github.com/jridgway

# Postal address (add as many lines as necessary)
address:
  - line: 22 Clearview Ave
  - line: Princeton, NJ 08540

# Build settings
markdown: kramdown
permalink: pretty
